services:
  app:
    container_name: seismic-app
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - DJANGO_SETTINGS_MODULE=backend_core.settings
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - PYTHONUNBUFFERED=1
      - POSTGRES_DB=seismic_catalog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db
    restart: unless-stopped
    command: ["python", "/app/scripts/docker_entrypoint.py"]

  db:
    image: postgis/postgis:16-3.4
    container_name: seismic-db
    restart: always
    environment:
      - POSTGRES_DB=seismic_catalog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_LOGGING_COLLECTOR=off
      - POSTGRES_LOG_MIN_MESSAGES=error
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backup:
    build: .
    container_name: seismic-backup
    depends_on:
      - db
    environment:
      - ENTRYPOINT_MODE=backup
      - POSTGRES_DB=seismic_catalog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - BACKUP_INTERVAL_SECONDS=86400
      - BACKUP_RETENTION_DAYS=7
    volumes:
      - ./data/backups:/backups
    command: ["python", "/app/scripts/docker_entrypoint.py"]
    restart: unless-stopped

volumes:
  postgres_data: